# backups
alias backup-dropbox-vault-to-storage1-vault='rsync -r -t -p -o -g -x -v --progress --delete -s /home/webartifex/vaults/dropbox-vault/ /home/webartifex/vaults/storage1-vault/backups/vault/'
alias backup-dropbox-vault-to-storage2-vault='rsync -r -t -p -o -g -x -v --progress --delete -s /home/webartifex/vaults/dropbox-vault/ /home/webartifex/vaults/storage2-vault/backups/vault/'
alias backup-dropbox-vault-to-storage3-vault='rsync -r -t -p -o -g -x -v --progress --delete -s /home/webartifex/vaults/dropbox-vault/ /home/webartifex/vaults/storage3-vault/backups/vault/'

# decrypt/un-decrypt vaults
alias open-dropbox-vault='gocryptfs -q -extpass "pass misc/dropbox-vault" $HOME/.dropbox/.sync/Dropbox/vault/ $HOME/vaults/dropbox-vault'
alias close-dropbox-vault='fusermount -q -u $HOME/vaults/dropbox-vault'
alias open-storage1-vault='gocryptfs -q -extpass "pass misc/storage-vaults" /media/$USER/wa-Storage1/ $HOME/vaults/storage1-vault'
alias close-storage1-vault='fusermount -q -u $HOME/vaults/storage1-vault'
alias open-storage2-vault='gocryptfs -q -extpass "pass misc/storage-vaults" /media/$USER/wa-Storage2/ $HOME/vaults/storage2-vault'
alias close-storage2-vault='fusermount -q -u $HOME/vaults/storage2-vault'
alias open-storage3-vault='gocryptfs -q -extpass "pass misc/storage-vaults" /media/$USER/wa-Storage3/ $HOME/vaults/storage3-vault'
alias close-storage3-vault='fusermount -q -u $HOME/vaults/storage3-vault'
alias open-DATATRAVEL-vault='gocryptfs -q -extpass "pass misc/usb-stick-vaults" /media/$USER/DATATRAVEL/.vault/ $HOME/vaults/DATATRAVEL-vault'
alias close-DATATRAVEL-vault='fusermount -q -u $HOME/vaults/DATATRAVEL-vault'
alias open-INFORMS-vault='gocryptfs -q -extpass "pass misc/usb-stick-vaults" /media/$USER/INFORMS/.vault/ $HOME/vaults/INFORMS-vault'
alias close-INFORMS-vault='fusermount -q -u $HOME/vaults/INFORMS-vault'
alias open-KUEHNE-vault='gocryptfs -q -extpass "pass misc/usb-stick-vaults" /media/$USER/KUEHNE/.vault/ $HOME/vaults/KUEHNE-vault'
alias close-KUEHNE-vault='fusermount -q -u $HOME/vaults/KUEHNE-vault'
alias open-TRANSCEND-vault='gocryptfs -q -extpass "pass misc/usb-stick-vaults" /media/$USER/TRANSCEND/.vault/ $HOME/vaults/TRANSCEND-vault'
alias close-TRANSCEND-vault='fusermount -q -u $HOME/vaults/TRANSCEND-vault'
