sudo apt-get install -y\
    bat\
    bleachbit\
    calibre\
    cloc\
    cmake\
        cmake-doc\
    cmatrix\
    colordiff\
    curl\
    discord\
    exuberant-ctags\
    fd-find\
    flatpak\
    gimp\
        gimp-help-en\
    gnome-tweaks\
    gnupg\
        gpg-agent\
        gpgsm\
        parcimonie\
        pinentry-gtk2 pinentry-doc\
        scdaemon
    gnutls-bin\
    gocryptfs\
    gpw\
    httpie\
    hunspell\
        hunspell-de-de\
    imagemagick\
        imagemagick-doc\
    julia\
        julia-doc\
    libnotify-bin\
    libreoffice-calc\
        libreoffice-impress\
        libreoffice-writer\
    make\
        make-doc\
    mdp\
    mlocate\
    net-tools\
    nodejs\
        npm\
    gparted\
    gstreamer1.0-libav\
        gstreamer1.0-plugins-bad\
        gstreamer1.0-plugins-good\
        gstreamer1.0-plugins-ugly\
        libavcodec-extra\
    htop\
    libpam-tmpdir\
    locales-all\
    pandoc\
    pass\
    pavucontrol\
    pwgen\
    r-base\
        r-base-core\
        libcurl4-openssl-dev\
    ranger\
    rsync\
        grsync\
    screenfetch\
    spotify-client\
    sqlite3\
        sqlite3-doc\
        sqlitebrowser\
    synaptic\
    telegram-desktop\
    texlive\
        texlive-xetex\
        texmaker\
        fonts-lyx\
    thunderbird\
        enigmail\
    tree\
    usb-creator-gtk\
    uuid\
    xclip\
    ufw\
        gufw\
    usbguard\
    vim\
        vim-doc\
        vim-julia\
        vim-python-jedi\
        vim-scripts\
    vlc\
    wget\
    zsh\
        zsh-doc
