echo -e '\n\033[36m\033[2m\033[1m\033[7mCreating mount folders for gocryptfs vaults\033[0m\n'
mkdir -p "$HOME/vaults/dropbox-vault"
ln -fs "$HOME/vaults/dropbox-vault" "$HOME/documents/vault"
mkdir -p "$HOME/vaults/storage1-vault"
mkdir -p "$HOME/vaults/storage2-vault"
mkdir -p "$HOME/vaults/storage3-vault"
mkdir -p "$HOME/vaults/DATATRAVEL-vault"
mkdir -p "$HOME/vaults/INFORMS-vault"
mkdir -p "$HOME/vaults/KUEHNE-vault"
mkdir -p "$HOME/vaults/TRANSCEND-vault"
